# Generated by Django 5.1.1 on 2024-12-06 16:40

import django.db.models.deletion
import markdownx.models
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', markdownx.models.MarkdownxField(verbose_name='Tavsif')),
                ('description_uz', markdownx.models.MarkdownxField(null=True, verbose_name='Tavsif')),
                ('description_ru', markdownx.models.MarkdownxField(null=True, verbose_name='Tavsif')),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Filial nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Filial nomi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('address_uz', models.TextField(null=True, verbose_name='Manzil')),
                ('address_ru', models.TextField(null=True, verbose_name='Manzil')),
                ('location', models.CharField(max_length=255, verbose_name='Lokatsiya (Yandex Maps Link)')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Ish vaqtlari')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif (ixtiyoriy)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name="Chegirma (-so'mda)")),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Chegirmaning boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Chegirmaning tugash vaqti')),
            ],
            options={
                'db_table': 'promo_codes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_id', models.PositiveBigIntegerField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('language_code', models.CharField(choices=[('uz', 'O‘zbekcha'), ('ru', 'Русский')], default='uz', max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('isQrCode', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'telegram_users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib Raqami')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tgbot.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery', models.CharField(choices=[('pickup', 'Borib olish'), ('delivery', 'Yetkazish')], default='pickup', max_length=50)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokatsiya (Yandex Maps Link)')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=50)),
                ('addention', models.TextField(blank=True, null=True)),
                ('is_all_order_info_filled', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tgbot.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tgbot.user')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('telegram_payment_charge_id', models.CharField(max_length=255)),
                ('provider_payment_charge_id', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tgbot.order')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name="Chegirma (so'm)")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='tgbot.category', verbose_name='Kategoriya')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tgbot.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
            options={
                'db_table': 'bot_admins',
            },
        ),
    ]
