# Generated by Django 5.1.1 on 2025-01-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_product_code_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iiko_order_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('DeliveryPickUp', 'Borib olish'), ('DeliveryByCourier', 'Yetkazish')], max_length=50),
        ),
    ]
